language: node_js
node_js: 10
env:
  - NODE_ENV=ci
  - NODE_ENV=ci-staging
cache: yarn

variables:
    CARGO_HOME: "$CI_PROJECT_DIR/.cargo"
    RUSTUP_HOME: "$CI_PROJECT_DIR/.rustup"

stages:
  - install
  - install-tests
  - build
  - test

install_dependencies:
  tags: 
    - docker
  stage: install
  script:
    - yarn --force

install_test_dependencies:
  tags: 
    - docker
  stage: install-tests
  script:
    - cd tests && yarn && yarn remove near-runtime-ts && yarn add ../

build_test_wasm:
  tags: 
    - docker
  stage: build
  script:
    - cd tests && yarn build

build_near_vm_runner_standalone:
  tags: 
    - docker
  stage: build
  script:
    - export PATH="$PATH:$CARGO_HOME/bin"
    - cd tests && ./build-near-vm-runner-standalone.sh

run_aspect_tests:
  tags: 
    - docker
  stage: test
  script:
    - cd tests && yarn asp

run_assembly_test:
  tags: 
    - docker
  stage: test
  script:
    - cd tests && ./test.sh


